### ISSUE TITLE
Error compiling example with LVGL version 9.1.0

### ISSUE THREAD

**Issue by vinny-888** [espressif/esp-box#152]
When I try to compile the chat_gpt example I get an error which seems to be due to the LVGL version

```
/git/esp-box/examples/chatgpt_demo/factory_nvs/main/ui/images/ui_img_setup_text_bg_png.c:1217:13: error: 'lv_image_header_t' has no member named 'always_zero'
 1217 |     .header.always_zero = 0,
      |             ^~~~~~~~~~~
/git/esp-box/examples/chatgpt_demo/factory_nvs/main/ui/images/ui_img_setup_text_bg_png.c:1221:18: error: 'LV_IMG_CF_TRUE_COLOR_ALPHA' undeclared here (not in a function)
 1221 |     .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /git/esp-box/examples/chatgpt_demo/factory_nvs/build/log/idf_py_stderr_output_93222 and /git/esp-box/examples/chatgpt_demo/factory_nvs/build/log/idf_py_stdout_output_93222
```

I see at the top of the file in the error this LVGL version: 8.3.4

When I check my dependencies.lock I see

```
  lvgl/lvgl:
    component_hash: 2a8f619b5c2b1c7ad116c33d43dae8989c76739068f406a7e8ba9221e1085f17
    source:
      service_url: https://api.components.espressif.com/
      type: service
    version: 9.1.0
```

I cannot seem to find any info on how to change the LVGL version tho.

Any help much appreciated
